name: Check Inactive Issues

on:
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - develop
      - issue#21294
      - release-*
  pull_request:
    branches:
      - develop
      - release-*

jobs:
  check-inactive-issues:
    name: Check Inactive Issues
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
        
    - name: Merge develop branch into the current branch
      uses: ./.github/actions/merge
        
    - name: Initialize Containers
      run: |
        make build
        make stop

    - name: Check inactive issues
      env:
        GITHUB_TOKEN: ${{ secrets.ASHU_GITHUB_TOKEN }}
      run: |
        make inactive_issue_checker
      
    - name: Report failure if failed on oppia/oppia develop branch
      if: ${{ failure() && github.event_name == 'push' && github.repository == 'oppia/oppia' && github.ref == 'refs/heads/develop' }}
      uses: ./.github/actions/send-webhook-notification
      with:
        message: "Inactive issue check failed on the upstream develop branch."
        webhook-url: ${{ secrets.BUILD_FAILURE_ROOM_WEBHOOK_URL }}